# Generated by Django 2.2.7 on 2021-09-11 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MsgFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_friends_user', to='scauth.AuthUser', verbose_name='发送消息的用户')),
            ],
            options={
                'verbose_name': '好友表',
                'verbose_name_plural': '好友表',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('msg_type', models.CharField(blank=True, choices=[('Img', 'Img'), ('Word', 'Word')], default='Word', max_length=100, null=True, verbose_name='消息内容')),
                ('msg_content', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='消息内容')),
                ('msg_img', models.ImageField(blank=True, null=True, upload_to='msg_img/%Y/%m/%d/', verbose_name='聊天图片')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('send_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_send_user', to='scauth.AuthUser', verbose_name='发送消息的用户')),
            ],
            options={
                'verbose_name': '消息表',
                'verbose_name_plural': '消息表',
            },
        ),
    ]
