# Generated by Django 2.2.7 on 2021-09-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='coinfamily', max_length=100, verbose_name='用户名')),
                ('password', models.CharField(default='', max_length=100, verbose_name='用户密码')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_img/%Y/%m/%d/', verbose_name='头像')),
                ('phone', models.CharField(default='', max_length=100, verbose_name='手机号码')),
                ('eamail', models.CharField(default='', max_length=100, verbose_name='邮箱')),
                ('weichat', models.CharField(default='', max_length=100, verbose_name='微信')),
                ('telegram', models.CharField(default='', max_length=100, verbose_name='电报账号')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='登陆次数')),
                ('token', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='用户token')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
        ),
    ]
