# Generated by Django 2.2.7 on 2021-09-10 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('title', models.CharField(default='', max_length=512, verbose_name='事件标题')),
                ('detail', models.CharField(default='', max_length=10000, verbose_name='事件详情')),
                ('mark', models.CharField(default='', max_length=512, verbose_name='事件备注')),
                ('status', models.CharField(choices=[('WAIT_CHECK', 'WAIT_CHECK'), ('WAAIT_SOLUTE', 'WAAIT_SOLUTE'), ('WAIT_BACK', 'WAIT_BACK'), ('FINISH', 'FINISH')], default='WAIT_CHECK', max_length=100, verbose_name='事件状态')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='事件浏览次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '事件表',
                'verbose_name_plural': '事件表',
            },
        ),
        migrations.CreateModel(
            name='EventCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='', max_length=100, verbose_name='类别名称')),
                ('detail', models.CharField(default='', max_length=512, verbose_name='类别说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
            ],
            options={
                'verbose_name': '事件类别表',
                'verbose_name_plural': '事件类别表',
            },
        ),
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='论坛内容')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='查看次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_comment_reply', to='cevent.Event', verbose_name='关联事件')),
                ('father_forum_cy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cevent.EventComment', verbose_name='父评论')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_comment_reply_user', to='scauth.AuthUser', verbose_name='评论发布者')),
            ],
            options={
                'verbose_name': '事件评论回复表',
                'verbose_name_plural': '事件评论回复表',
            },
        ),
        migrations.CreateModel(
            name='EventBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('content', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='论坛内容')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='查看次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否是有效')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_back', to='cevent.Event', verbose_name='关联事件')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_back_user', to='scauth.AuthUser', verbose_name='反馈人')),
            ],
            options={
                'verbose_name': '事件用户反馈表',
                'verbose_name_plural': '事件用户反馈表',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='event_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goods_cat', to='cevent.EventCat', verbose_name='事件分类'),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_publish_user', to='scauth.AuthUser', verbose_name='事件发布人'),
        ),
    ]
