# Generated by Django 2.2.7 on 2021-09-12 11:01

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cevent', '0002_auto_20210912_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='detail',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='事件详情'),
        ),
        migrations.AlterField(
            model_name='eventback',
            name='content',
            field=DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='事件详情'),
        ),
    ]
