# Generated by Django 2.2.7 on 2021-09-12 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevent', '0003_auto_20210912_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='coin',
            field=models.CharField(default='', max_length=512, verbose_name='币种'),
        ),
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.CharField(default='', max_length=512, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='event',
            name='hacker_address',
            field=models.CharField(default='', max_length=512, verbose_name='黑客地址'),
        ),
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], db_index=True, default='No', max_length=100, verbose_name='是不是商家'),
        ),
        migrations.AddField(
            model_name='event',
            name='my_address',
            field=models.CharField(default='', max_length=512, verbose_name='自己的地址'),
        ),
        migrations.AddField(
            model_name='event',
            name='weichat',
            field=models.CharField(default='', max_length=512, verbose_name='微信'),
        ),
    ]
