# Generated by Django 2.2.7 on 2021-09-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cevent', '0004_auto_20210912_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcomment',
            old_name='father_forum_cy',
            new_name='father_event_cy',
        ),
    ]
