# Generated by Django 2.2.7 on 2021-09-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevent', '0005_auto_20210912_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_new',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], db_index=True, default='No', max_length=100, verbose_name='是否最新'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_public',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], db_index=True, default='No', max_length=100, verbose_name='是否公开'),
        ),
    ]
