# Generated by Django 2.2.7 on 2021-09-10 15:36

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(default='', max_length=70, verbose_name='工具名称')),
                ('excerpt', models.TextField(default='', max_length=200, verbose_name='工具简介')),
                ('img', models.ImageField(blank=True, null=True, upload_to='article/%Y/%m/%d/', verbose_name='工具封面')),
                ('github', models.CharField(default='', max_length=70, verbose_name='工具github地址')),
                ('body', DjangoUeditor.models.UEditorField(blank=True, verbose_name='工具详细介绍')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='查看次数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '工具表',
                'verbose_name_plural': '工具表',
            },
        ),
    ]
