# Generated by Django 2.2.7 on 2021-09-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='gitee',
            field=models.CharField(default='', max_length=70, verbose_name='工具gitee地址'),
        ),
    ]
